/** @type {import('jest').Config} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  transform: {
    '^.+\\.tsx?$': ['ts-jest', { tsconfig: 'tsconfig.test.json' }],
  },
  roots: ['<rootDir>/tests/unit'],
  setupFiles: ['<rootDir>/tests/setup/environment.ts'],
  testMatch: ['**/*.test.ts'],
  collectCoverageFrom: [
    'src/core/**/*.ts',
    'src/analytics/**/*.ts',
    'src/audit/**/*.ts',
    'src/background/**/*.ts',
    'src/debugging/**/*.ts',
    'src/bridge/**/*.ts',
    'src/simulation/**/*.ts',
    'src/storage/**/*.ts',
    'src/testing/**/*.ts',
    'src/timeline/**/*.ts',
    'src/observability/**/*.ts',
    'src/reliability/**/*.ts',
    'src/focus/**/*.ts',
    'src/governance/**/*.ts',
    'src/health/**/*.ts',
    'src/integrations/**/*.ts',
    'src/notifications/**/*.ts',
    'src/recovery/**/*.ts',
    'src/reflection/**/*.ts',
    'src/safety/**/*.ts',
    'src/scheduling/**/*.ts',
    'src/hibernation/**/*.ts',
    'src/triggers/**/*.ts',
    'src/commands/**/*.ts',
    'src/comparison/**/*.ts',
    'src/configuration/**/*.ts',
    'src/knowledge/**/*.ts',
    'src/memory/**/*.ts',
    'src/orchestration/**/*.ts',
    '!src/core/diagnostics.ts',
  ],
  coverageDirectory: '<rootDir>/coverage',
  coverageReporters: ['text', 'lcov'],
  // Ratchet: set a few points below the current measured coverage so a genuine
  // regression fails the build, without making unrelated refactors brittle.
  // Current: 95.4% statements / 89.49% branches / 96.44% functions / 98.15% lines.
  coverageThreshold: {
    global: {
      branches: 87,
      functions: 94,
      lines: 96,
      statements: 93,
    },
  },
  clearMocks: true,
  restoreMocks: true,
};
